name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
       python-version: 3.9
    - run: pip install flake8
    - run: pip install mypy
    - run: flake8 FaceSwap/roop/run.py 
    - run: mypy FaceSwap/roop/run.py 
   test:
    strategy:
     matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker image tag
      run: echo "IMAGE_TAG=mohammedhamdy98/face-swap-fastapi-docker:$(date +%s)" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . --file FaceSwap/dockerfile.gpu --tag ${{ env.IMAGE_TAG }}
      
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}
